server:
  port: ${NAYARIT_COBROS_ABIERTOS_SERVICE_PORT:8080}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: nayarit
      repositories:
        enabled: true

  application:
    name: cobros-abiertos-service